version: "2"
services:
    web:
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/usr/share/nginx/app
            - ./node_modules:/usr/share/nginx/node_modules
            - ./projects:/usr/share/nginx/projects
            - ./certificate.pem:/home/certificate.pem
            - ./key.pem:/home/key.pem
            - ./default.conf:/etc/nginx/conf.d/default.conf
